// Fill out your copyright notice in the Description page of Project Settings.

#include "RshipActorRegistrationComponent.h"
#include "Engine/World.h"
#include "Engine/Engine.h"
#include "RshipSubsystem.h"
#include "GameFramework/Actor.h"
#include "Logs.h"
#include "Core/RshipTargetContributor.h"
#include "Controllers/RshipControllerComponent.h"

void URshipActorRegistrationComponent::OnRegister()
{
	Super::OnRegister();
	PrimaryComponentTick.bCanEverTick = false;
	SetComponentTickEnabled(false);
	Register();
}

void URshipActorRegistrationComponent::OnComponentDestroyed(bool bDestoryHierarchy)
{
	if (GEngine)
	{
		if (URshipSubsystem* Subsystem = GEngine->GetEngineSubsystem<URshipSubsystem>())
		{
			Subsystem->UnregisterTargetComponent(this);
		}
	}

	if (TargetData)
	{
		TargetData->SetBoundTargetComponent(nullptr);
		delete TargetData;
		TargetData = nullptr;
	}

	Super::OnComponentDestroyed(bDestoryHierarchy);
}

void URshipActorRegistrationComponent::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);
}

void URshipActorRegistrationComponent::OnDataReceived()
{
	OnRshipData.Broadcast();
}

TArray<FString> URshipActorRegistrationComponent::BuildFullParentTargetIds(const FString& ServiceId) const
{
	TArray<FString> Result;
	Result.Reserve(ParentTargetIds.Num());

	for (const FString& ParentId : ParentTargetIds)
	{
		const FString Trimmed = ParentId.TrimStartAndEnd();
		if (Trimmed.IsEmpty())
		{
			continue;
		}

		if (Trimmed.Contains(TEXT(":")))
		{
			Result.Add(Trimmed);
		}
		else
		{
			Result.Add(ServiceId + TEXT(":") + Trimmed);
		}
	}

	return Result;
}

void URshipActorRegistrationComponent::Reconnect()
{
	if (URshipSubsystem* Subsystem = GEngine->GetEngineSubsystem<URshipSubsystem>())
	{
		Subsystem->RefreshTargetCache();
	}
}

FString URshipActorRegistrationComponent::GetFullTargetId() const
{
	if (TargetData)
	{
		return TargetData->GetId();
	}

	if (!GEngine)
	{
		return targetName;
	}

	if (URshipSubsystem* Subsystem = GEngine->GetEngineSubsystem<URshipSubsystem>())
	{
		return targetName.Contains(TEXT(":")) ? targetName : (Subsystem->GetServiceId() + TEXT(":") + targetName);
	}

	return targetName;
}

FRshipTargetProxy URshipActorRegistrationComponent::GetTargetProxy() const
{
	if (!GEngine)
	{
		return FRshipTargetProxy();
	}

	URshipSubsystem* Subsystem = GEngine->GetEngineSubsystem<URshipSubsystem>();
	if (!Subsystem)
	{
		return FRshipTargetProxy();
	}

	if (TargetData)
	{
		return FRshipTargetProxy(Subsystem, TargetData->GetId());
	}

	const FString FullTargetId = GetFullTargetId();
	return FullTargetId.IsEmpty() ? FRshipTargetProxy() : FRshipTargetProxy(Subsystem, FullTargetId);
}

void URshipActorRegistrationComponent::Register()
{
	UWorld* World = GetWorld();
	if (World && World->WorldType == EWorldType::EditorPreview)
	{
		UE_LOG(LogRshipExec, Verbose, TEXT("Skipping registration for blueprint preview actor: %s"), *targetName);
		return;
	}

	URshipSubsystem* Subsystem = GEngine ? GEngine->GetEngineSubsystem<URshipSubsystem>() : nullptr;
	AActor* Parent = GetOwner();
	if (!Subsystem || !Parent)
	{
		UE_LOG(LogRshipExec, Warning, TEXT("Register failed: missing subsystem or owner"));
		return;
	}

	Subsystem->BeginRegistrationBatch();

	FString OutlinerName = Parent->GetName();
#if WITH_EDITOR
	OutlinerName = Parent->GetActorLabel();
#endif

	// Keep default target IDs in sync with duplicated/renamed actors before registration.
	// Manual/custom target IDs are preserved.
	const bool bIsUnset = targetName.IsEmpty();
	const bool bMatchesPreviousAuto = !AutoGeneratedTargetNameBaseline.IsEmpty() && targetName == AutoGeneratedTargetNameBaseline;
	if (bIsUnset || bMatchesPreviousAuto)
	{
		const FString PreviousTargetName = targetName;
		targetName = OutlinerName;
		AutoGeneratedTargetNameBaseline = targetName;

		if (bIsUnset)
		{
			UE_LOG(LogRshipExec, Log, TEXT("Target Id not set, defaulting to actor name: %s"), *targetName);
		}
		else if (PreviousTargetName != targetName)
		{
			UE_LOG(LogRshipExec, Log, TEXT("Default Target Id refreshed from actor name: %s -> %s"), *PreviousTargetName, *targetName);
		}
	}
	else if (targetName == OutlinerName)
	{
		AutoGeneratedTargetNameBaseline = targetName;
	}

	const FString FullTargetId = Subsystem->GetServiceId() + TEXT(":") + targetName;
	const TArray<FString> FullParentTargetIds = BuildFullParentTargetIds(Subsystem->GetServiceId());

	if (TargetData != nullptr)
	{
		const FString ExistingTargetId = TargetData->GetId();
		const bool bIdentityChanged = ExistingTargetId != FullTargetId;
		if (bIdentityChanged)
		{
			UE_LOG(LogRshipExec, Log, TEXT("Register detected target identity change '%s' -> '%s'; rebuilding target"), *ExistingTargetId, *FullTargetId);
			Unregister();
		}
		else
		{
			TargetData->SetName(targetName);
			TargetData->SetParentTargetIds(FullParentTargetIds);
			TargetData->SetBoundTargetComponent(this);
			Subsystem->RegisterTargetComponent(this);
			RebindSiblingContributors();
			Subsystem->EndRegistrationBatch();
			UE_LOG(LogRshipExec, Verbose, TEXT("Register refreshed existing target in place: %s"), *FullTargetId);
			return;
		}
	}

	TargetData = new Target(FullTargetId, Subsystem);
	TargetData->SetName(targetName);
	TargetData->SetParentTargetIds(FullParentTargetIds);
	TargetData->SetBoundTargetComponent(this);
	Subsystem->RegisterTargetComponent(this);

	RebindSiblingContributors();

	Subsystem->EndRegistrationBatch();

	UE_LOG(LogRshipExec, Log, TEXT("Component Registered: %s (actions=%d emitters=%d)"), *Parent->GetName(), TargetData->GetActions().Num(), TargetData->GetEmitters().Num());
}

bool URshipActorRegistrationComponent::HasTag(const FString& Tag) const
{
	const FString NormalizedTag = Tag.TrimStartAndEnd().ToLower();
	for (const FString& ExistingTag : Tags)
	{
		if (ExistingTag.TrimStartAndEnd().ToLower() == NormalizedTag)
		{
			return true;
		}
	}
	return false;
}

void URshipActorRegistrationComponent::Unregister()
{
	if (!GEngine)
	{
		return;
	}

	URshipSubsystem* Subsystem = GEngine->GetEngineSubsystem<URshipSubsystem>();
	if (!Subsystem)
	{
		return;
	}

	Subsystem->UnregisterTargetComponent(this);

	if (TargetData)
	{
		TargetData->SetBoundTargetComponent(nullptr);
		delete TargetData;
		TargetData = nullptr;
	}

	UE_LOG(LogRshipExec, Log, TEXT("Target unregistered: %s"), *targetName);
}

void URshipActorRegistrationComponent::SetTargetId(const FString& NewTargetId)
{
	if (NewTargetId.IsEmpty())
	{
		UE_LOG(LogRshipExec, Warning, TEXT("SetTargetId called with empty ID - ignoring"));
		return;
	}

	if (targetName == NewTargetId)
	{
		return;
	}

	const FString OldTargetId = targetName;
	if (TargetData != nullptr)
	{
		Unregister();
	}

	targetName = NewTargetId;
	AutoGeneratedTargetNameBaseline.Empty();
	Register();

	UE_LOG(LogRshipExec, Log, TEXT("Target ID changed: %s -> %s"), *OldTargetId, *NewTargetId);
}

void URshipActorRegistrationComponent::RebindSiblingContributors()
{
	AActor* Owner = GetOwner();
	if (!Owner)
	{
		return;
	}

	TArray<UActorComponent*> Components;
	Owner->GetComponents(Components);
	for (UActorComponent* Component : Components)
	{
		if (!Component || Component == this)
		{
			continue;
		}

		if (URshipControllerComponent* Controller = Cast<URshipControllerComponent>(Component))
		{
			Controller->RegisterRshipTargets();
			continue;
		}

		IRshipTargetContributor* Contributor = Cast<IRshipTargetContributor>(Component);
		if (Contributor)
		{
			Contributor->RegisterRshipTargets();
		}
	}
}
